project:
  type: website
  output-dir: docs
  

website:
  title: "Kabier's Page"
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "Kabier Izzeldin, University of Toronto @ 2024"
  navbar:
    right:
      - href: index.qmd
        text: home
      - href: blog.qmd
        text: blog
      - href: twwc.qmd
        text: twwc
      - href: files/FinalCV.pdf
        text: cv
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: Morph
    css: styles.css

editor: visual

execute:
  freeze: auto  # re-render only when source changes
  
